input_size: [3, 112, 112]
color_space: 'RGB'
name: 'ir101'
output_dim: 512
start_from: '/workspace/face-recognition/codes/CVLface/cvlface/pretrained_models/adaface_ir101_webface12m/model.pt'
freeze: False