
data_root: ${oc.env:DATA_ROOT}
rec: 'webface260m/WebFace4M'
color_space: 'RGB'
num_classes: 205990
num_image: 4235242

repeated_sampling_cfg:
  use_same_image: False
  second_img_augment: False
  ldmk_path: 'ldmk_5points.csv'
  disable_repeat: True  # performs repeated aug without increasing batch size
  skip_aug_prob_in_disable_repeat: 0.0
  repeated_augment_prob: 0.1
semi_sampling_cfg: null
resample_dataset: ''