data_root: "/home/user1/"
eval_every_n_epochs: 1
per_epoch_evaluations: {
  "eval": {
    'path': 'newdata/eval_data',
    'evaluation_type': 'verification',
    'color_space': 'RGB',
    'batch_size': 128,
    'num_workers': 16
  },
}