# quick.yaml
data_root: "/home/user1/"
eval_every_n_epochs: 1

per_epoch_evaluations:
  lfw:
    path: "Download/facerec_val/lfw"
    evaluation_type: "verification"
    color_space: "RGB"
    batch_size: 128
    num_workers: 8

  agedb_30:
    path: "Download/facerec_val/agedb_30"
    evaluation_type: "verification"
    color_space: "RGB"
    batch_size: 128
    num_workers: 8

  cfpfp:
    path: "Download/facerec_val/cfp_fp"
    evaluation_type: "verification"
    color_space: "RGB"
    batch_size: 128
    num_workers: 8

  cplfw:
    path: "Download/facerec_val/cplfw"
    evaluation_type: "verification"
    color_space: "RGB"
    batch_size: 128
    num_workers: 8

  calfw:
    path: "Download/facerec_val/calfw"
    evaluation_type: "verification"
    color_space: "RGB"
    batch_size: 128
    num_workers: 8

  newdata_eval:
    path: "newdata/eval_data"
    evaluation_type: "verification"
    color_space: "RGB"
    batch_size: 128
    num_workers: 8

  tinyface_eval:
    path: "Download/facerec_val/tinyface_aligned_pad_0.1"
    evaluation_type: "tinyface"
    color_space: "RGB"
    batch_size: 128
    num_workers: 8
