dynamic_paths:
  log: "logs/{stream_id}.log"

public:
  log_level: "INFO"

vector_search:
  url: http://localhost:19530
  collection_name: test_collection

database:
  elasticsearch:
    url: https://elastic:W=s_wUTYO2ueQHP5vHjj@192.168.130.54:9200
    index: bina_system

minio:
  base_url: https://cdn-bavar.d.aiengines.ir
  endpoint: cdn-bavar.d.aiengines.ir
  access_key: 
    shared-user1: I3NUOzimJFo6qsKCfWFeSQ
    shared-user2: YBljhNUfjuByuw90dlXR9OQ00
    shared-user3: UterhLoQXXEc+Ri6+XRYEl
  secret_key: CN0CjBqBQFR0YWvX3UvklpLTDRBpbsgYAznOJJyL
  bucket: ai-shared
  object_name: 'process/{stream_id}/{dir_name}/{name}'


fr:
  landmark: 0.85
  face_detection: 0.2
  face_surface: 1000
  looklike: 0.55

small_pose: True
