input_size: [3, 112, 112]
color_space: 'RGB'
name: 'base'
output_dim: 512
start_from: ''
freeze: False

mask_ratio: 0.0
rpe_config:
  name: iRPE
  rpe_on: qkv
  shared_head: True
  mode: ctx
  method: product
  ratio: 1.9
  ctx_type: ''
  num_keypoints: 5